test

diff --git a/.github/workflows/label.yml b/.github/workflows/label.yml
--- a/.github/workflows/label.yml
+++ b/.github/workflows/label.yml
@@ -1,16 +1,20 @@
-name: Label PR
+name: Do Not Merge
 
 on:
+  workflow_dispatch:
   pull_request:
+    types: [synchronize, opened, reopened, labeled, unlabeled]
 
 jobs:
-    label:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Label PR
-            uses: actions/github-script@v3
-            with:
-              github-token: ${{ secrets.GITHUB_TOKEN }}
-              script: |
-                  const labels = ["needs-review"];
-                  core.info(github.pull_request.labels)
+  merge-guard:
+    name: Prevent Merging
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for label
+        if: ${{ contains(github.event.*.labels.*.name, 'bug') }}
+        run: |
+          echo "Pull request is labeled as 'do not merge'"
+          echo "This workflow fails so that the pull request cannot be merged"
+          exit 1
+      - name: Ok
+        run: echo "Pull request is not labeled as 'do not merge'"
